---
- name: Monitor critical directory changes
  hosts: all
  sources:
    - ansible.eda.file_watch:
        path: /var/log
        recursive: true
        patterns: ['*']
        ignore_patterns: ['*.tmp']
        events: ['modified', 'created', 'deleted', 'moved']
  
  rules:
    - name: Detect directory changes
      condition: event.type == "modified" or event.type == "created" or event.type == "deleted" or event.type == "moved"
      action:
        run_job_template:
          name: DirectoryRemediation
          organization: Default
          include_events: true
          job_args:
            affected_path: "{{ event.path }}"
            change_type: "{{ event.type }}"
            timestamp: "{{ event.timestamp }}"
            