---
- name: Monitor critical directory changes
  hosts: all
  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    - ansible.eda.file_watch:
        path: /var/log
        recursive: true
        patterns: ['*']
        ignore_patterns: ['*.tmp']
        events: ['modified', 'created', 'deleted', 'moved']
  
  rules:
    - name: Webhook Event
      condition: true
      action:
        debug:
          msg: "Webhook event detected"
    - name: Detect directory changes
      condition: event.payload.type == "modified" orevent.payload.type == "created" orevent.payload.type == "deleted" orevent.payload.type == "moved"
      action:
        run_job_template:
          name: DirectoryRemediation
          organization: Default
          include_events: true
          job_args:
            affected_path: "{{event.payload.path }}"
            change_type: "{{event.payload.type }}"
            timestamp: "{{event.payload.timestamp }}"
            