---
- name: Monitor critical directory changes
  hosts: all
  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    - ansible.eda.file_watch:
        path: /var/log
        recursive: true
        patterns: ['*']
        ignore_patterns: ['*.tmp']
        events: ['modified', 'created', 'deleted', 'moved']
  
  rules:
    - name: Webhook Event
      condition: true
      action:
        debug:
          msg: "Webhook event detected"
    - name: Detect directory changes
      condition: payload.event.type == "modified" or payload.event.type == "created" or payload.event.type == "deleted" or payload.event.type == "moved"
      action:
        run_job_template:
          name: DirectoryRemediation
          organization: Default
          include_events: true
          job_args:
            affected_path: "{{ payload.event.path }}"
            change_type: "{{ payload.event.type }}"
            timestamp: "{{ payload.event.timestamp }}"
            